@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue Nov 23 10:42:52 +0100 2021
REM SW Build 2615518 on Fri Aug  9 15:55:25 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 1dd12cef56534136a4cd9c754a0df6d3 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot Cmpt0to3_tb_behav xil_defaultlib.Cmpt0to3_tb -log elaborate.log"
call xelab  -wto 1dd12cef56534136a4cd9c754a0df6d3 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot Cmpt0to3_tb_behav xil_defaultlib.Cmpt0to3_tb -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
